package com.nettakrim.souper_secret_settings;

import net.minecraft.sound.SoundEvent;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.math.random.Random;

public class RandomSound {
    public static void Play() {
        int size = soundEvents.length;
        Random random = SouperSecretSettingsClient.getGameRendererAccessor().getRandom();
        SoundEvent sound = soundEvents[random.nextInt(size)];
        if (SouperSecretSettingsClient.client.player != null) SouperSecretSettingsClient.client.player.playSound(sound, 1, (random.nextFloat() * random.nextFloat() * 2) + 0.5f);
    }

    private static final SoundEvent[] soundEvents = {
        SoundEvents.ENTITY_ALLAY_AMBIENT_WITHOUT_ITEM,
        SoundEvents.ENTITY_ALLAY_AMBIENT_WITH_ITEM,
        SoundEvents.AMBIENT_UNDERWATER_LOOP,
        SoundEvents.AMBIENT_UNDERWATER_LOOP_ADDITIONS,
        SoundEvents.AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE,
        SoundEvents.AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE,
        SoundEvents.BLOCK_AMETHYST_BLOCK_CHIME,
        SoundEvents.BLOCK_BEEHIVE_WORK,
        SoundEvents.BLOCK_BELL_RESONATE,
        SoundEvents.ITEM_AXE_SCRAPE,
        SoundEvents.ENTITY_CAT_BEG_FOR_FOOD,
        SoundEvents.ENTITY_CAT_DEATH,
        SoundEvents.BLOCK_CHORUS_FLOWER_GROW,
        SoundEvents.BLOCK_CONDUIT_AMBIENT,
        SoundEvents.BLOCK_CONDUIT_ATTACK_TARGET,
        SoundEvents.BLOCK_CORAL_BLOCK_BREAK,
        SoundEvents.ENTITY_COW_MILK,
        SoundEvents.ENTITY_CREEPER_PRIMED,
        SoundEvents.ENTITY_DOLPHIN_DEATH,
        SoundEvents.ENTITY_DONKEY_DEATH,
        SoundEvents.ENTITY_ELDER_GUARDIAN_AMBIENT,
        SoundEvents.ENTITY_ELDER_GUARDIAN_CURSE,
        SoundEvents.BLOCK_ENCHANTMENT_TABLE_USE,
        SoundEvents.BLOCK_ENDER_CHEST_CLOSE,
        SoundEvents.ENTITY_ENDER_DRAGON_DEATH,
        SoundEvents.ENTITY_ENDER_DRAGON_GROWL,
        SoundEvents.ENTITY_ENDER_EYE_DEATH,
        SoundEvents.ENTITY_ENDERMAN_TELEPORT,
        SoundEvents.BLOCK_END_PORTAL_SPAWN,
        SoundEvents.ENTITY_EVOKER_AMBIENT,
        SoundEvents.ENTITY_EVOKER_CAST_SPELL,
        SoundEvents.ENTITY_EVOKER_DEATH,
        SoundEvents.ENTITY_EVOKER_PREPARE_ATTACK,
        SoundEvents.ENTITY_EVOKER_PREPARE_SUMMON,
        SoundEvents.ENTITY_EVOKER_PREPARE_WOLOLO,
        SoundEvents.ENTITY_EXPERIENCE_ORB_PICKUP,
        SoundEvents.ENTITY_FIREWORK_ROCKET_TWINKLE,
        SoundEvents.ENTITY_FOX_DEATH,
        SoundEvents.ENTITY_FOX_SCREECH,
        SoundEvents.ENTITY_GENERIC_EXPLODE.value(),
        SoundEvents.ENTITY_GHAST_AMBIENT,
        SoundEvents.ENTITY_GHAST_HURT,
        SoundEvents.ENTITY_GHAST_SCREAM,
        SoundEvents.ENTITY_GHAST_WARN,
        SoundEvents.ENTITY_GOAT_SCREAMING_AMBIENT,
        SoundEvents.ENTITY_GOAT_SCREAMING_DEATH,
        SoundEvents.ENTITY_GOAT_SCREAMING_MILK,
        SoundEvents.ENTITY_GUARDIAN_AMBIENT_LAND,
        SoundEvents.ENTITY_HORSE_DEATH,
        SoundEvents.ENTITY_ILLUSIONER_MIRROR_MOVE,
        SoundEvents.ENTITY_ILLUSIONER_PREPARE_BLINDNESS,
        SoundEvents.ENTITY_ILLUSIONER_PREPARE_MIRROR,
        SoundEvents.ENTITY_LIGHTNING_BOLT_IMPACT,
        SoundEvents.ENTITY_LIGHTNING_BOLT_THUNDER,
        SoundEvents.ENTITY_LLAMA_SPIT,
        SoundEvents.ENTITY_PANDA_DEATH,
        SoundEvents.ENTITY_PANDA_SNEEZE,
        SoundEvents.ENTITY_PIGLIN_BRUTE_CONVERTED_TO_ZOMBIFIED,
        SoundEvents.ENTITY_PLAYER_SPLASH,
        SoundEvents.ENTITY_PLAYER_SPLASH_HIGH_SPEED,
        SoundEvents.ENTITY_PUFFER_FISH_BLOW_OUT,
        SoundEvents.ENTITY_PUFFER_FISH_BLOW_UP,
        SoundEvents.ENTITY_PUFFER_FISH_STING,
        SoundEvents.ENTITY_RAVAGER_AMBIENT,
        SoundEvents.ENTITY_RAVAGER_ROAR,
        SoundEvents.ENTITY_RAVAGER_DEATH,
        SoundEvents.ENTITY_RAVAGER_STUNNED,
        SoundEvents.BLOCK_RESPAWN_ANCHOR_AMBIENT,
        SoundEvents.BLOCK_RESPAWN_ANCHOR_CHARGE,
        SoundEvents.BLOCK_RESPAWN_ANCHOR_SET_SPAWN,
        SoundEvents.BLOCK_SCULK_CATALYST_FALL,
        SoundEvents.BLOCK_SCULK_SENSOR_CLICKING,
        SoundEvents.BLOCK_SCULK_SHRIEKER_SHRIEK,
        SoundEvents.ENTITY_SHULKER_AMBIENT,
        SoundEvents.ENTITY_SKELETON_CONVERTED_TO_STRAY,
        SoundEvents.ENTITY_SKELETON_HORSE_DEATH,
        SoundEvents.ENTITY_SLIME_SQUISH,
        SoundEvents.ENTITY_STRIDER_DEATH,
        SoundEvents.ENCHANT_THORNS_HIT,
        SoundEvents.ENTITY_TNT_PRIMED,
        SoundEvents.ITEM_TOTEM_USE,
        SoundEvents.ITEM_TRIDENT_HIT_GROUND,
        SoundEvents.ITEM_TRIDENT_THUNDER.value(),
        SoundEvents.ENTITY_TURTLE_HURT,
        SoundEvents.ENTITY_WANDERING_TRADER_DISAPPEARED,
        SoundEvents.ENTITY_WANDERING_TRADER_DRINK_MILK,
        SoundEvents.ENTITY_WANDERING_TRADER_REAPPEARED,
        SoundEvents.ENTITY_WARDEN_ANGRY,
        SoundEvents.ENTITY_WARDEN_HEARTBEAT,
        SoundEvents.ENTITY_WARDEN_NEARBY_CLOSEST,
        SoundEvents.ENTITY_WARDEN_SONIC_BOOM,
        SoundEvents.ENTITY_WARDEN_SONIC_CHARGE,
        SoundEvents.ENTITY_WITCH_AMBIENT,
        SoundEvents.ENTITY_WITCH_DEATH,
        SoundEvents.ENTITY_WITCH_DRINK,
        SoundEvents.ENTITY_WITHER_AMBIENT,
        SoundEvents.ENTITY_WITHER_DEATH,
        SoundEvents.ENTITY_WOLF_AMBIENT,
        SoundEvents.ENTITY_WOLF_SHAKE,
        SoundEvents.ENTITY_WOLF_WHINE,
        SoundEvents.ENTITY_ZOMBIE_CONVERTED_TO_DROWNED,
        SoundEvents.ENTITY_ZOMBIE_DESTROY_EGG,
        SoundEvents.ENTITY_ZOMBIE_HORSE_DEATH,
        SoundEvents.ENTITY_ZOMBIE_VILLAGER_CONVERTED,
        SoundEvents.ENTITY_ZOMBIE_VILLAGER_CURE,
        SoundEvents.ENTITY_ZOMBIE_VILLAGER_DEATH,
        SoundEvents.ENTITY_CAMEL_AMBIENT,
        SoundEvents.ENTITY_CAMEL_DEATH,
        SoundEvents.ENTITY_CAMEL_DASH,
        SoundEvents.ENTITY_SNIFFER_SNIFFING,
        SoundEvents.ENTITY_SNIFFER_DEATH,
        SoundEvents.ENTITY_SNIFFER_IDLE,
        SoundEvents.ENTITY_SNIFFER_DIGGING_STOP,
        SoundEvents.ENTITY_SNIFFER_HAPPY,
        SoundEvents.BLOCK_TRIAL_SPAWNER_BREAK,
        SoundEvents.BLOCK_TRIAL_SPAWNER_DETECT_PLAYER,
        SoundEvents.BLOCK_TRIAL_SPAWNER_SPAWN_MOB,
        SoundEvents.BLOCK_TRIAL_SPAWNER_OPEN_SHUTTER,
        SoundEvents.BLOCK_TRIAL_SPAWNER_EJECT_ITEM,
        SoundEvents.BLOCK_TRIAL_SPAWNER_OMINOUS_ACTIVATE,
        SoundEvents.AMBIENT_CAVE.value(),
        SoundEvents.ENTITY_BREEZE_JUMP,
        SoundEvents.ENTITY_BREEZE_IDLE_AIR,
        SoundEvents.ITEM_MACE_SMASH_GROUND_HEAVY,
        SoundEvents.ITEM_MACE_SMASH_AIR,
        SoundEvents.BLOCK_CHEST_LOCKED,
        SoundEvents.ENTITY_ARMADILLO_DEATH,
        SoundEvents.ENTITY_ARMADILLO_PEEK,
        SoundEvents.ENTITY_ARMADILLO_AMBIENT
    };
}
