package com.nettakrim.souper_secret_settings;

import dev.dannytaylor.luminance.client.data.ClientData;
import dev.dannytaylor.perspective.seam.mixin.client.render.GameRendererAccessor;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.util.RandomSource;

public class RandomSound {
    public static void play() {
        LocalPlayer player = ClientData.minecraft.player;
        if (player != null) {
            int size = soundEvents.length;
            RandomSource random = ((GameRendererAccessor)ClientData.minecraft.gameRenderer).seam$getRandom();
            SoundEvent sound = soundEvents[random.nextInt(size)];
            player.playSound(sound, 1, (random.nextFloat() * random.nextFloat() * 2) + 0.5f);
        }
    }

    private static final SoundEvent[] soundEvents = {
            SoundEvents.ALLAY_AMBIENT_WITHOUT_ITEM,
            SoundEvents.ALLAY_AMBIENT_WITH_ITEM,
            SoundEvents.AMBIENT_UNDERWATER_LOOP,
            SoundEvents.AMBIENT_UNDERWATER_LOOP_ADDITIONS,
            SoundEvents.AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE,
            SoundEvents.AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE,
            SoundEvents.AMETHYST_BLOCK_CHIME,
            SoundEvents.BEEHIVE_WORK,
            SoundEvents.BELL_RESONATE,
            SoundEvents.AXE_SCRAPE,
            SoundEvents.CAT_BEG_FOR_FOOD,
            SoundEvents.CAT_DEATH,
            SoundEvents.CHORUS_FLOWER_GROW,
            SoundEvents.CONDUIT_AMBIENT,
            SoundEvents.CONDUIT_ATTACK_TARGET,
            SoundEvents.CORAL_BLOCK_BREAK,
            SoundEvents.COW_MILK,
            SoundEvents.CREEPER_PRIMED,
            SoundEvents.DOLPHIN_DEATH,
            SoundEvents.DONKEY_DEATH,
            SoundEvents.ELDER_GUARDIAN_AMBIENT,
            SoundEvents.ELDER_GUARDIAN_CURSE,
            SoundEvents.ENCHANTMENT_TABLE_USE,
            SoundEvents.ENDER_CHEST_CLOSE,
            SoundEvents.ENDER_DRAGON_DEATH,
            SoundEvents.ENDER_DRAGON_GROWL,
            SoundEvents.ENDER_EYE_DEATH,
            SoundEvents.ENDERMAN_TELEPORT,
            SoundEvents.END_PORTAL_SPAWN,
            SoundEvents.EVOKER_AMBIENT,
            SoundEvents.EVOKER_CAST_SPELL,
            SoundEvents.EVOKER_DEATH,
            SoundEvents.EVOKER_PREPARE_ATTACK,
            SoundEvents.EVOKER_PREPARE_SUMMON,
            SoundEvents.EVOKER_PREPARE_WOLOLO,
            SoundEvents.EXPERIENCE_ORB_PICKUP,
            SoundEvents.FIREWORK_ROCKET_TWINKLE,
            SoundEvents.FOX_DEATH,
            SoundEvents.FOX_SCREECH,
            SoundEvents.GENERIC_EXPLODE.value(),
            SoundEvents.GHAST_AMBIENT,
            SoundEvents.GHAST_HURT,
            SoundEvents.GHAST_SCREAM,
            SoundEvents.GHAST_WARN,
            SoundEvents.GOAT_SCREAMING_AMBIENT,
            SoundEvents.GOAT_SCREAMING_DEATH,
            SoundEvents.GOAT_SCREAMING_MILK,
            SoundEvents.GUARDIAN_AMBIENT_LAND,
            SoundEvents.HORSE_DEATH,
            SoundEvents.ILLUSIONER_MIRROR_MOVE,
            SoundEvents.ILLUSIONER_PREPARE_BLINDNESS,
            SoundEvents.ILLUSIONER_PREPARE_MIRROR,
            SoundEvents.LIGHTNING_BOLT_IMPACT,
            SoundEvents.LIGHTNING_BOLT_THUNDER,
            SoundEvents.LLAMA_SPIT,
            SoundEvents.PANDA_DEATH,
            SoundEvents.PANDA_SNEEZE,
            SoundEvents.PIGLIN_BRUTE_CONVERTED_TO_ZOMBIFIED,
            SoundEvents.PLAYER_SPLASH,
            SoundEvents.PLAYER_SPLASH_HIGH_SPEED,
            SoundEvents.PUFFER_FISH_BLOW_OUT,
            SoundEvents.PUFFER_FISH_BLOW_UP,
            SoundEvents.PUFFER_FISH_STING,
            SoundEvents.RAVAGER_AMBIENT,
            SoundEvents.RAVAGER_ROAR,
            SoundEvents.RAVAGER_DEATH,
            SoundEvents.RAVAGER_STUNNED,
            SoundEvents.RESPAWN_ANCHOR_AMBIENT,
            SoundEvents.RESPAWN_ANCHOR_CHARGE,
            SoundEvents.RESPAWN_ANCHOR_SET_SPAWN,
            SoundEvents.SCULK_CATALYST_FALL,
            SoundEvents.SCULK_CLICKING,
            SoundEvents.SCULK_SHRIEKER_SHRIEK,
            SoundEvents.SHULKER_AMBIENT,
            SoundEvents.SKELETON_CONVERTED_TO_STRAY,
            SoundEvents.SKELETON_HORSE_DEATH,
            SoundEvents.SLIME_SQUISH,
            SoundEvents.STRIDER_DEATH,
            SoundEvents.THORNS_HIT,
            SoundEvents.TNT_PRIMED,
            SoundEvents.TOTEM_USE,
            SoundEvents.TRIDENT_HIT_GROUND,
            SoundEvents.TRIDENT_THUNDER.value(),
            SoundEvents.TURTLE_HURT,
            SoundEvents.WANDERING_TRADER_DISAPPEARED,
            SoundEvents.WANDERING_TRADER_DRINK_MILK,
            SoundEvents.WANDERING_TRADER_REAPPEARED,
            SoundEvents.WARDEN_ANGRY,
            SoundEvents.WARDEN_HEARTBEAT,
            SoundEvents.WARDEN_NEARBY_CLOSEST,
            SoundEvents.WARDEN_SONIC_BOOM,
            SoundEvents.WARDEN_SONIC_CHARGE,
            SoundEvents.WITCH_AMBIENT,
            SoundEvents.WITCH_DEATH,
            SoundEvents.WITCH_DRINK,
            SoundEvents.WITHER_AMBIENT,
            SoundEvents.WITHER_DEATH,
            SoundEvents.WOLF_SHAKE,
            SoundEvents.ZOMBIE_CONVERTED_TO_DROWNED,
            SoundEvents.ZOMBIE_DESTROY_EGG,
            SoundEvents.ZOMBIE_HORSE_DEATH,
            SoundEvents.ZOMBIE_VILLAGER_CONVERTED,
            SoundEvents.ZOMBIE_VILLAGER_CURE,
            SoundEvents.ZOMBIE_VILLAGER_DEATH,
            SoundEvents.CAMEL_AMBIENT,
            SoundEvents.CAMEL_DEATH,
            SoundEvents.CAMEL_DASH,
            SoundEvents.SNIFFER_SNIFFING,
            SoundEvents.SNIFFER_DEATH,
            SoundEvents.SNIFFER_IDLE,
            SoundEvents.SNIFFER_DIGGING_STOP,
            SoundEvents.SNIFFER_HAPPY,
            SoundEvents.TRIAL_SPAWNER_BREAK,
            SoundEvents.TRIAL_SPAWNER_DETECT_PLAYER,
            SoundEvents.TRIAL_SPAWNER_SPAWN_MOB,
            SoundEvents.TRIAL_SPAWNER_OPEN_SHUTTER,
            SoundEvents.TRIAL_SPAWNER_EJECT_ITEM,
            SoundEvents.TRIAL_SPAWNER_OMINOUS_ACTIVATE,
            SoundEvents.AMBIENT_CAVE.value(),
            SoundEvents.BREEZE_JUMP,
            SoundEvents.BREEZE_IDLE_AIR,
            SoundEvents.MACE_SMASH_GROUND_HEAVY,
            SoundEvents.MACE_SMASH_AIR,
            SoundEvents.CHEST_LOCKED,
            SoundEvents.ARMADILLO_DEATH,
            SoundEvents.ARMADILLO_PEEK,
            SoundEvents.ARMADILLO_AMBIENT,
            SoundEvents.CREAKING_ACTIVATE,
            SoundEvents.CREAKING_TWITCH,
            SoundEvents.CREAKING_HEART_BREAK,
            SoundEvents.PALE_HANGING_MOSS_IDLE,
            SoundEvents.HAPPY_GHAST_AMBIENT,
            SoundEvents.HAPPY_GHAST_DEATH,
            SoundEvents.HAPPY_GHAST_HURT,
            SoundEvents.DRIED_GHAST_AMBIENT_WATER,
            SoundEvents.DRIED_GHAST_TRANSITION
    };
}
