# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 2.2.0-mc1.21.11
maven_group = com.nettakrim.souper_secret_settings
archives_base_name = souper_secret_settings

# Dependencies
fabric_version=0.141.3+1.21.11
quilt_config = 1.2.0
modmenu = 17.0.0